# Welcome to SHENQINGLINGBLOG!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
# baseurl: http://localhost:4000

# Site settings
title: welcome to my blog! # ex. I m Chuan
name: shenqingling # ex. DONGChuan
email: sql370@qq.com
location: Shanghai, China # ex. Nice, France
# company: MyCompany
company_url: my_company_website
github_url: https://github.com/shenqingling # ex. https://github.com/DONGChuan
description: description_of_your_web_site
favicon: favicon.png # Image must be in assets/images
repository: github_username/github_username.github.io # ex. DONGChuan/DONGChuan.github.io

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  #-
  #  href: /open-source
  #  label: Open-Source

  #-
  #  href: /blog
  #  label: Blog

  #-
  #  href: /bookmark
  #  label: Bookmark

  #-
  #  href: /about
  #  label: About